version: '3'

services:
  app:
    image: my-app-dev:alpine3.15
    build: .
    container_name: my-app-dev
    user: "gituser:gituser"
    volumes:
      - ./:/usr/src/app
      #exclude files in volume
      - /usr/src/app/.ssh
    working_dir: "/usr/src/app"
    tty: true
